# Generated by Django 4.1.2 on 2022-10-15 16:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bearing', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(359)])),
                ('length', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('length_unit', models.CharField(choices=[('m', 'meters'), ('ft', 'feet')], default='m', max_length=2)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='airports.airport')),
            ],
        ),
    ]
