# Generated by Django 4.1.2 on 2022-10-15 20:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hangar',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('spaces', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaneModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model_number', models.CharField(max_length=10)),
                ('manufacturer', models.CharField(max_length=50)),
                ('fuel_capacity', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('fuel_unit', models.CharField(choices=[('l', 'litres'), ('gal', 'gallons')], default='l', max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='Plane',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plane_number', models.CharField(max_length=10)),
                ('hangar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes', to='airports.hangar')),
                ('plane_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planes', to='airports.planemodel')),
            ],
        ),
        migrations.AddField(
            model_name='hangar',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hangars', to='airports.airport'),
        ),
    ]
