# Generated by Django 4.1.2 on 2022-10-15 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airports', '0002_hangar_planemodel_alter_airport_name_plane_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planemodel',
            name='efficiency_unit',
            field=models.CharField(choices=[('mpg', 'miles per gallon'), ('km/l', 'kilometers per litre')], default='mpg', max_length=4),
        ),
        migrations.AddField(
            model_name='planemodel',
            name='fuel_efficiency',
            field=models.PositiveIntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planemodel',
            name='fuel_unit',
            field=models.CharField(choices=[('l', 'litres'), ('gal', 'gallons')], default='l', max_length=4),
        ),
    ]
